import React, { useEffect, useState } from "react";

type CurrencyResp = { currency?: string } | null;

export default function PrivacyPage() {
  const [currency, setCurrency] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let mounted = true;
    async function getCurrency() {
      try {
        const res = await fetch("https://api.bareuptime.co/ip/currency", {
          headers: { "Content-Type": "application/json" },
        });
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const json: CurrencyResp = await res.json();
        if (!mounted) return;
        setCurrency(json?.currency ?? null);
      } catch (err: any) {
        console.error(err);
        if (mounted) setError(String(err?.message ?? err));
      } finally {
        if (mounted) setLoading(false);
      }
    }
    getCurrency();
    return () => {
      mounted = false;
    };
  }, []);

  function renderIndiaPolicy() {
    const highlightBox: React.CSSProperties = {
      background: '#fff7f0',
      border: '1px solid #ffd1a9',
      padding: 16,
      borderRadius: 6,
      marginTop: 8,
      marginBottom: 16,
    };

    return (
      <div>
        <h1 style={{ marginTop: 0 }}>Privacy Policy</h1>
        <p>Last updated: February 05, 2024</p>
        <p>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </p>
        <h2>Interpretation and Definitions</h2>
        <h3>Interpretation</h3>
        <p>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </p>
        <h3>Definitions</h3>
        <p>For the purposes of this Privacy Policy:</p>
        <ul>
          <li>Account means a unique account created for You to access our Service or parts of our Service.</li>
          <li>Affiliate means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
          <li>Company (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to M/s SNORKELL ASSOCIATES and CO., Office No. 415 OK Plus Spaces, Near Apex Circle, Malviya Industrial Area, Jaipur- 302017.</li>
          <li>Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
          <li>Country refers to: Rajasthan, India</li>
          <li>Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
          <li>Personal Data is any information that relates to an identified or identifiable individual.</li>
          <li>Service refers to the Website.</li>
          <li>Service Provider means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
          <li>Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li>Website refers to hith.chat, accessible from www.hith.chat</li>
          <li>You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        <h3>Collecting and Using Your Personal Data</h3>
        <h4>Types of Data Collected</h4>
        <h5>Personal Data</h5>
        <p>
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but
          is not limited to: Email address, First name and last name, Address, State, Province, ZIP/Postal code, City
        </p>

        <h5>Usage Data</h5>
        <p>
          Usage Data is collected automatically when using the Service. Usage
          Data may include information such as Your Device's Internet Protocol
          address (e.g. IP address), browser type, browser version, the pages
          of our Service that You visit, the time and date of Your visit, the
          time spent on those pages, unique device identifiers and other
          diagnostic data.
        </p>

        <h4>Tracking Technologies and Cookies</h4>
        <p>
          We use Cookies and similar tracking technologies to track the
          activity on Our Service and store certain information. Tracking
          technologies used are beacons, tags, and scripts to collect and
          track information and to improve and analyze Our Service.
        </p>

        <h4>Use of Your Personal Data</h4>
        <p>
          The Company may use Personal Data for the following purposes: To
          provide and maintain our Service, To manage Your Account, For the
          performance of a contract, To contact You, To provide You with news
          and offers, To manage Your requests, For business transfers, For
          other purposes such as analysis and improvement.
        </p>

        <h4>Retention of Your Personal Data</h4>
        <p>
          The Company will retain Your Personal Data only for as long as is
          necessary for the purposes set out in this Privacy Policy.
        </p>

        <h4>Transfer of Your Personal Data</h4>
        <p>
          Your information, including Personal Data, is processed at the
          Company's operating offices and in any other places where the
          parties involved in the processing are located.
        </p>

        <h4>Delete Your Personal Data</h4>
        <p>
          You have the right to delete or request that We assist in deleting
          the Personal Data that We have collected about You.
        </p>

        <h4>Disclosure of Your Personal Data</h4>
        <p>
          The Company may disclose Your Personal Data in certain situations
          including business transactions, law enforcement, and other legal
          requirements.
        </p>

        <h4 style={{ color: '#7a1f1f' }}>Security of Your Personal Data</h4>
        <div style={highlightBox}>
          <p style={{ margin: 0, fontWeight: 600 }}>
            The security of Your Personal Data is important to us, but remember
            that no method of transmission over the Internet, or method of
            electronic storage is 100% secure.
          </p>
        </div>

        <h4>Children's Privacy</h4>
        <p>
          Our Service does not address anyone under the age of 13. We do not
          knowingly collect personally identifiable information from anyone
          under the age of 13.
        </p>

        <h4>Changes to this Privacy Policy</h4>
        <p>
          We may update Our Privacy Policy from time to time. We will notify
          You of any changes by posting the new Privacy Policy on this page.
        </p>

        <h4>Contact Us</h4>
        <p>
          If you have any questions about this Privacy Policy, You can contact
          us: By email: support@hith.chat; By visiting: www.hith.chat; Address: M/s SNORKELL ASSOCIATES and CO., Office No. 415 OK Plus Spaces, Near Apex Circle, Malviya Industrial Area, Jaipur- 302017, Rajasthan, India
        </p>

        <p>This Privacy Policy is governed by the laws of Rajasthan, India.</p>
      </div>
    );
  }

  function renderUSPolicy() {
    const highlightBox: React.CSSProperties = {
      background: '#fff7f0',
      border: '1px solid #ffd1a9',
      padding: 16,
      borderRadius: 6,
      marginTop: 8,
      marginBottom: 16,
    };

    return (
      <div>
        <h1 style={{ marginTop: 0 }}>Privacy Policy</h1>
        <p>Effective Date: June 24, 2025</p>
        <p>Last Updated: June 24, 2025</p>
        <h2>1. Introduction</h2>
        <p>
          Penify Technologies LLC ("we," "our," or "us") operates BareUptime,
          a website monitoring service. This Privacy Policy explains how we
          collect, use, disclose, and safeguard your information when you use
          our website monitoring service ("Service") and website located at
          https://hith.chat (the "Website").
        </p>

        <h2>2. Company Information</h2>
        <p>
          Company: Penify Technologies LLC<br />
          Registered Address: 30 N Gould St Ste N, Sheridan, WY 82801<br />
          Email: support@hith.chat<br />
          Website: https://hith.chat
        </p>

        <h2>3. Information We Collect</h2>
        <h3>3.1 Personal Information</h3>
        <p>
          Account Information: Email address, name, and password when you
          create an account
        </p>
        <p>Contact Information: Email addresses for notifications and communications</p>
        <p>Payment Information: Billing address and payment method details (processed securely through third-party payment processors)</p>

        <h3>3.2 Technical Information</h3>
        <p>
          Website URLs, Monitoring Data, Usage Data, Device Information such
          as IP address, browser type, operating system, and device
          identifiers.
        </p>

        <h3>3.3 Communication Data</h3>
        <p>Support Communications and Newsletter Subscriptions</p>

        <h2>4. How We Use Your Information</h2>
        <p>
          We use your information to provide, operate, and maintain our
          monitoring Service; send monitoring alerts and notifications; process
          payments; improve and personalize your experience; communicate
          about updates and support; send marketing communications (with your
          consent); and comply with legal obligations.
        </p>

        <h2>5. Information Sharing</h2>
        <p>We do not sell, trade, or rent your personal information. We may share information with service providers, for legal requirements, or business transfers.</p>

        <h3>5.1 Service Providers</h3>
        <p>Payment processors (Stripe, PayPal), Cloud hosting providers (AWS, Google Cloud), Email service providers, Analytics services.</p>

        <h3>5.2 Legal Requirements</h3>
        <p>We may disclose information when required by law or legal process.</p>

        <h3>5.3 Business Transfers</h3>
        <p>In the event of a merger, acquisition, or sale of assets, your information may be transferred.</p>

        <h2 style={{ color: '#7a1f1f' }}>6. Data Security</h2>
        <div style={highlightBox}>
          <p style={{ margin: 0, fontWeight: 600 }}>
            We implement appropriate technical and organizational security measures to protect your information, including:

            Encryption of data in transit and at rest
            Secure authentication mechanisms
            Regular security assessments
            Access controls and employee training
            However, no method of transmission over the internet is 100% secure, and we cannot guarantee absolute security.
          </p>
        </div>

        <h2>7. Your Rights</h2>
        <p>Depending on your location, you may have rights such as access, correction, deletion, portability, and opt-out. To exercise these rights, contact privacy@hith.chat.</p>

        <h2>8. Contact Us</h2>
        <p>
          Email: privacy@hith.chat<br />
          Address: Penify Technologies LLC, 30 N Gould St Ste N, Sheridan, WY 82801
        </p>

        <p>This Privacy Policy is governed by the laws of the State of Wyoming, United States.</p>
      </div>
    );
  }

  return (
    <div style={{ padding: 20, display: 'flex', justifyContent: 'center' }}>
      <div style={{ maxWidth: 900, width: '100%' }}>
        {loading && <p>Loading privacy policy...</p>}
        {error && <p style={{ color: "red" }}>Failed to load policy: {error}</p>}
        {!loading && !error && (
          <div>
            {currency === "INR" ? renderIndiaPolicy() : renderUSPolicy()}
          </div>
        )}
      </div>
    </div>
  );
}
